@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TAccess << (T,lightGrey) >> {  Boolean isWrite  Boolean isRead  Boolean isReadWriteUnknown}class TAccessible << (T,lightGrey) >> {  Number numberOfAccessingMethods  Number numberOfAccesses  Number numberOfLocalAccesses  Number numberOfAccessingClasses  Number numberOfGlobalAccesses}class TWithAccesses << (T,lightGrey) >> {}TAccess " *incomingAccesses" -- "variable" TAccessibleTAccess " *accesses" -- "accessor" TWithAccessesTAccessible -- " *accessors" TWithAccesses@enduml