@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class behavior1 as "TWithAccesses" << (T,lightGrey) >> {}class behavior2 as "TAccessible" << (T,lightGrey) >> {}class behavior3 as "TAccess" << (T,lightGrey) >> {	+ Boolean isWrite}behavior3 "accesses *" -[#black]- "accessor" behavior1behavior3 "incomingAccesses *" -[#black]- "variable" behavior2@enduml