@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TDereferencedInvocation << (T,lightGrey) >> {}class TWithDereferencedInvocations << (T,lightGrey) >> {}TDereferencedInvocation " *dereferencedInvocations" -- "referencer" TWithDereferencedInvocations@enduml