@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class behavior1 as "TFileInclude" << (T,lightGrey) >> {}class behavior2 as "TWithFileIncludes" << (T,lightGrey) >> {}behavior1 "outgoingIncludeRelations * " -[#black]- "source  " behavior2behavior1 "incomingIncludeRelations * " -[#black]- "target  " behavior2@enduml