@startumlhide empty membersclass behavior1 as "TWithInheritances" << (T,orchid) >> {}class behavior2 as "TInheritance" << (T,orchid) >> {}behavior2 "superInheritances * " -[#black]- "subclass  " behavior1behavior2 "subInheritances * " -[#black]- "superclass  " behavior1@enduml