@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class behavior1 as "TWithInheritances" << (T,lightGrey) >> {}class behavior2 as "TInheritance" << (T,lightGrey) >> {}behavior2 "superInheritances * " -[#black]- "subclass  " behavior1behavior2 "subInheritances * " -[#black]- "superclass  " behavior1@enduml