@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TInvocation << (T,lightGrey) >> {}class TWithInvocations << (T,lightGrey) >> {}class TInvocable << (T,lightGrey) >> {}class TInvocationsReceiver << (T,lightGrey) >> {}TInvocation " *receivingInvocations" -- "receiver" TInvocationsReceiverTInvocation " *outgoingInvocations" -- "sender" TWithInvocationsTInvocation " *incomingInvocations" -- " *candidates" TInvocable@enduml