@startumlhide empty membersclass behavior1 as "TInvocation" << (T,orchid) >> {}class behavior2 as "TInvocable" << (T,orchid) >> {}class behavior3 as "TInvocationsReceiver" << (T,orchid) >> {}class behavior4 as "TWithInvocations" << (T,orchid) >> {}behavior1 "outgoingInvocations * " -[#black]- "sender  " behavior4behavior1 "receivingInvocations * " -[#black]- "receiver  " behavior3behavior2 "candidates * " -[#black]- "incomingInvocations * " behavior1@enduml