@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TReference << (T,lightGrey) >> {}class TWithReferences << (T,lightGrey) >> {}class TReferenceable << (T,lightGrey) >> {}TReference " *incomingReferences" -- "referredType" TReferenceableTReference " *outgoingReferences" -- "referencer" TWithReferences@enduml