@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TLCOMMetrics << (T,lightGrey) >> {  Number lcom3  Number lcom2}class TSourceLanguage << (T,lightGrey) >> {}class TWithSourceLanguage << (T,lightGrey) >> {}class TUnknownSourceLanguage << (T,lightGrey) >> {}class TAssociationMetaLevelDependency << (T,lightGrey) >> {}class TOODependencyQueries << (T,lightGrey) >> {}class TEntityMetaLevelDependency << (T,lightGrey) >> {  Number numberOfChildren  Boolean isDead  Number fanOut  Number numberOfDeadChildren  Number fanIn}TEntityMetaLevelDependency <|-- TOODependencyQueriesTWithSourceLanguage " *sourcedEntities" -- "declaredSourceLanguage" TSourceLanguage@enduml