@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class behavior1 as "TLCOMMetrics" << (T,lightGrey) >> {}class behavior2 as "TWithSourceLanguage" << (T,lightGrey) >> {}class behavior3 as "TSourceLanguage" << (T,lightGrey) >> {}class behavior4 as "TUnknownSourceLanguage" << (T,lightGrey) >> {}behavior3 "declaredSourceLanguage  " -[#black]- "sourcedEntities * " behavior2@enduml