@startumlhide empty membersskinparam class {  BackgroundColor white  ArrowColor black  BorderColor darkGray}class TTraitUsage << (T,lightGrey) >> {}class TWithTraits << (T,lightGrey) >> {}class TTrait << (T,lightGrey) >> {}TTraitUsage " *incomingTraitUsages" -- "trait" TTraitTTrait " *traits" -- "traitOwner" TWithTraits@enduml